
const char * configXmlpart1 =
"<?xml version=\"1.0\" ?>\n"
"<work version=\"1.0.0.0\">\n"
"  <class key=\"archivator\" version=\"1.0.0.0\">\n"
"      <property key=\"numberOfThreads\" value=\"6\"/>\n"
"      <!-- Execution Type: analyze / production / -->\n"
"      <property key=\"executionType\" value=\"production\"/>\n"
"      <!-- Locate -->\n"
"      <property key=\"locale\" value=\"en\"/>\n"
"      <!-- Name of files for translation:\n"
"               exceptionsTranslation (_locate.txt v.g. exceptions_en.txt)\n"
"               ..\n"
"        -->\n"
"      <property key=\"exceptionsTranslation\" value=\"exceptions\"/>\n"
"\n"
"      <!-- Common log dir for all Archivator applications -->\n"
"      <property key=\"logDir\" value=\"/usr/local/cv_amu/data/www/logs/\"/>\n"
"  </class>\n"
"  <class key=\"Transformer\" version=\"1.0.0.0\">\n"
"     <property key=\"fileTransform\" value=\"coordinate_19.transform\"/>\n"
"  </class>\n"
"  <class key=\"Tracer\" version=\"1.0.0.0\">\n"
"    <!-- Set trace level to file and screen:\n"
"     debugLevel      = -D-,\n"
"         infoLevel       = -I-,\n"
"         warningLevel    = -W-,\n"
"         errorLevel      = -E-,\n"
"         fatalLevel      = -F-        -->\n"
"    <property key=\"levelScreen\" value=\"-D-,-W-,-I-,-E-,-F-\"/>\n"
"    <property key=\"levelFile\" value=\"-D-,-W-,-I-,-E-,-F-\"/>\n"
"    <!-- Message format:\n"
"          %1: Level\n"
"          %2: DateTime\n"
"          %3: Class Name\n"
"          %4: Function Name\n"
"          %5: Thread Id\n"
"          %6: Message\n"
"\n"
"     -->\n"
"    <property key=\"fmtMessage\"  value=\"%2 [PID:%5] %1 %3::%4 %6\"/>\n"
"    <property key=\"fmtDateTime\" value=\"yyyy-MM-dd hh:mm:ss\"/>\n"
"    <!-- is necessary to use values:\n"
"           %1 for Process [DBox/DUnbox]\n"
"           %2 JobId or ReelId -->\n"
"    <property key=\"traceFile\" value=\"%1_%2.log\"/>\n"
"  </class>\n"
"  <class key=\"Frame\" version=\"1.0.0.0\">\n"
"    <!--property key=\"forceTraced\" value=\"true\"/-->\n"
"  </class>\n"
"  <class key=\"BitUtils\" version=\"1.0.0.0\">\n"
"    <!--property key=\"forceTraced\" value=\"false\"/-->\n"
"  </class>\n"
"\n"
"  <class key=\"FrameBuilder\" version=\"1.0.0.0\">\n"
"    <!-- To format the message must consider:\n"
"      %1: The reel Id for the work (input in command line -->\n"
"    <property key=\"workDefinition\" value=\"reel%1.xml\"/>\n"
"  </class>\n"
"  <class key=\"FrameBuilder\">\n"
"    <!-- Output base folder for boxed files -->\n"
"    <property key=\"outputFile\" value=\"/usr/local/cv_amu/data/recording_reels/\"/>\n"
"    <!-- The type is: TIF\n"
"                      RAW\n"
"                      BMP\n"
"                      PNG -->\n";


const char * configXmlpart2 =
"    <property key=\"fileFormat\" value=\"RAW\"/>\n"
"  </class>\n"
"  <class key=\"ImageRaw\"  version=\"1.0.0.0\">\n"
"    <property key=\"adjustLen\" value=\"0\"/>\n"
"    <property key=\"crcMode\" value=\"64ISO\" />\n"
"    <property key=\"rawVersion\" value=\"1\" />\n"
"    <property key=\"crcOverAllData\" value=\"true\" />\n"
"    <property key=\"holes\" value=\"3\" />\n"
"  </class>\n"
"  <class key=\"TOC\" version=\"1.0.0.0\">\n"
"    <property key=\"colorDepth\" value=\"1\"/>\n"
"    <property key=\"blockSize\" value=\"1\" />\n"
"  </class>\n"
"  <class key=\"FrameUnbuilder\" version=\"1.0.0.0\">\n"
"    <property key=\"alias\" value=\"FrameBuilder\"/>\n"
"    <property key=\"transformMethod\" value=\"warp\"/>\n"
"    <!-- The parameter are: %1 is the frame ID -->\n"
"    <property key=\"inputDir\" value=\"/usr/local/cv_amu/data/nsca/%1/\"/>\n"
"    <!-- The parameter are: %1 is the job ID from restored data -->\n"
"    <property key=\"restoreDir\" value=\"/usr/local/cv_amu/data/restored/%1/\"/>\n"
"    <!-- The parameter are: %1 is the job ID from restored data -->\n"
"    <!-- This is for analyzer process -->\n"
"    <property key=\"originalDir\" value=\"/usr/local/cv_amu/data/original/%1/\"/>\n"
"  </class>\n"
"  <class key=\"DataLoader\" version=\"1.0.0.0\">\n"
"    <!-- accepted values are: pattern, file (with fileName property in FileDataFrameSource class) and random -->\n"
"    <property key=\"dataFrameSourceType\" value=\"file\"/>\n"
"  </class>\n"
"  <class key=\"SharpenFilter\" version=\"1.0.0.0\">\n"
"    <property key=\"amount\" value=\"100\"/>\n"
"    <property key=\"active\" value=\"true\"/>\n"
"    <property key=\"coefficients\" value=\"-0.085390  0.188372 -0.363868  0.188372 -0.085390; 0.188372 -0.499956  0.441212 -0.499956  0.188372; -0.363868  0.441212  1.500000  0.441212 -0.363868; 0.188372 -0.499956  0.441212 -0.499956  0.188372; -0.085390  0.188372 -0.363868  0.188372 -0.085390\"/>\n"
"  </class>\n"
"  <class key=\"tmp2sca\">\n"
"    <!-- This is the directory for scanned reels, copied here from scanner output dir\n"
"       when scanning is complete for a job. The value of %1 is the value from oi -->\n"
"    <property key=\"tmpDir\" value=\"/usr/local/cv_amu/data/scanning_reels/%1/\"/>\n"
"    <property key=\"modConvert\" value=\"-flop\"/>\n"
"  </class>\n"
"  <class key=\"crc64\">\n"
"    <property key=\"POLY64REV\" value=\"0x42F0E1EBA9EA3693\"/>\n"
"    <property key=\"INITIALCRC\" value=\"0x0000000000000000\"/>\n"
"  </class>\n"
"</work>\n";
